baseURL: 'https://blog.ramon-gordillo.dev/'
title: Architecting the deconstruction
enableRobotsTXT: true
enableEmoji: true
theme: jane
hasCJKLanguage: true
disableKinds: 
- "RSS"
disqusShortname: ''
googleAnalytics: ''
copyright: ''
defaultContentLanguage: en
languages:
  en:
    languageCode: en
params:
  author: 
    name: Ramon Gordillo
permalinks:
  post: /:year/:month/:title/
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      url: /
    - name: Archives
      weight: 20
      identifier: archives
      url: /post/
    - name: Tags
      weight: 30
      identifier: tags
      url: /tags/
    - name: Categories
      weight: 40
      identifier: categories
      url: /categories/
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokailight
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1